export const API_DEFAULTS = {
  PAGINATION: {
    DEFAULT_PAGE: 1,
    POSTS_PER_PAGE: 10,
    USER_POSTS_PER_PAGE: 12,
    COMMENTS_PER_PAGE: 20,
    MESSAGES_PER_PAGE: 50,
    FOLLOWERS_PER_PAGE: 20,
    FOLLOWING_PER_PAGE: 20,
    SUGGESTIONS_LIMIT: 5,
    SEARCH_RESULTS_PER_PAGE: 20,
    NOTIFICATIONS_PER_PAGE: 20,
  },
  TIMEOUT: 10000,
};

export const API_STATUS = {
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  SERVER_ERROR: 500,
};
